server:
  name: go-storage
  port: 8080

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

key_file: file

storage:
  bucket_name: name
  sub_directory: sub
  all_users_reader: true

provider: aws
google_credentials:
aws:
  region: abc
  access_key_id: abc
  secret_access_key: abc
