server:
  name: go-cloud-service
  port: 8080

key_file: file

provider: one-drive
#google-storage, google-drive, drop-box, one-drive

google_storage:
  bucket: go-firestore-rest-api.appspot.com
  directory: sub
  public: true

general_directory: golang-cloud-service
dropbox_token: J9uXB2sKcCsAAAAAAAAAATsNbQ1_HAdEqGtFPJEQJhD4_ePSL2Qh0lWheE50wzNb
# read README.md to know how to get drop-box token
one_drive_token: EwBwA8l6BAAUwihrrCrmQ4wuIJX5mbj7rQla6TUAAW2iAX5QjXkwjilLtZYoVH73CpZlJEbZ4reZNKatOl568d8Z2CYoFWF8ZIpaQeb1%2bxlryg4SREBmlSAd0sP0rg%2bpuj1vGdBzV%2bXgJ7bwVC5BXFJ6D4b8284F/GZxAaKF4E5c%2bMBtqqBpkC0oqStfq1BylzOLMSoe7vfjs1Gdfw5N0kvaVZAw7xBloHqgQq0gviCRl/ZPIpmeTn6ZUaY4lOdq4flou8o0B3/SLRTJqYcdnbiOmlWlZQ3hKpLgAyYqvErHZzzFS9olB1lIi98lHK6/WhukVNxXFvYe82o0tUhSBXT31fQiAaYKIVgcOU95Cy8GD885Rhg%2baC7TT%2bi//mYDZgAACIxX22DrguT4QAI4PGgHjQ/AJNOICdIAcQQe64q1Ncb5LplSBmKC%2bbzAucQmGoBNo8dVQV/tRdryyYGDuZgCyFk2WlSlO/DlJXrB1Ca0H0WL2yHfS4Yzs7UcRHkudm4YuJyssqDGt/nd9f5owt6vNMRSuGGTojgYd69wZzQG7R8yWdJldrKUULN3jF199aWNMtYhb2oNfKqK2EOc2ySayFKpNbOY3Je1ged451ml4OZFrx65XAY%2bBcrbjH8/MVenY1fCgGYaXUXC%2bf4bjVJ38QCdBvjftVN/SJtVGVrXEORknGI%2bv6dqGJUHqyQZCXA7n78jMuFG6Rkjd9sI91rfyIYw0heLP6bFo9QpZ2nn3o0GaQ1JJo0/Y90EdQ/r/aqzqA4ktbUag%2b0su1L2RPFnlP8ka/vs4gaRXMkW06MnWBQvQL9lb1ySh9cmOuD5BBdz2Y%2bopIpoL8cXxuolxlGJkOINQZyuTkq7iSlq3U3Lu5lbCcnwhNgTv5wulObSMqh60p5LBt/hFzco8m9cG%2bPe%2b9nokoKBvL6Y49hck%2b9AMzfipRk3DrVz2N4IGccP5dHBN6WMlW%2blbyfg6gZfmAhJG/ZdI1f9Q1bIFZhQg3Sf3r4JRaI8ooYHahRAXMB0xE0w8FI2acBgoxzLVxcI6AYgFJsu%2bcRhg0BTf%2bzASH1N25My8BoeIr9xmE%2bNfNoxJvQt3qFlhc%2bxEF/jemQJ1JrG4lvbpqe4PImEaQudr8PiEulkMp3Ja9T/9BddwjbjrVf0Q2Eq7//IgWC/EWyFAg%3d%3d
# read README.md to know how to get one-drive access token

google_credentials: '
  {
    "type": "service_account",
    "project_id": "crypto-airlock-335904",
    "private_key_id": "fd64e528691d731eac8d1a71add6e0333357c46a",
    "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDuHvh3e/iGPFw+\nEmoBBcHxzQ8Dx7xfeoHrvYogeh1seJ91ZLBPA3+9XRobEJ9LSeVrTQqhsyLfjeQn\nmeJN/fO6Qp8GrG8c1ZiyeY4uusRN5DSRIzubFPXp2FkJjTL0WbzJfqriu9C4JyCn\nAn/LvZiD5/shgw+gbpdlsq5d9xn0EkqMWqGem7i2ujeYOcf8FGM9I65vfXe0v9p7\nGAq6xLkUnTl3pwb9iLzrTW8vqXWAAwGvzV5mkUwqh9Y8dccEEe4C26PlQm/TBhqa\na1a4JdioJiN2mkxw6Y4I8NVOIKliAra997TpywqRnXN+Jn05uO+Kf7MUoZ5q6Jad\nisAu8s9bAgMBAAECggEAJQVpUZZTdiH7S2aXLC/beT8NjGO+N0VM3rxvYGDr+ISB\nHNd54TGk52mKrgDga0GtarMl1IG33x7ohSRT1Bayu9eGHEZXLhn4AsOK+1vr5O+h\nIUbjilcba+8dhLJ7D2obmQ4u/k+qAdTfgD0PZmXvSOQac27fe+zFxWN0NZq94mgK\nzobzfgCT01UY8JHvCmuBmFuoHPwrvxtv/PKzGasbKNW3cu5hJTFD2xRpYe/gBtg7\nCbmzEoDXUMn9c7SM7s1/NcUY0WKTCqgM0YipxqAdZS2chnM3PAXsWXb3n9B0FnT7\na7/ETZ7ybt9rz46aCVS38SSLl//cEK+b9Tl8Rqe6PQKBgQD96etyXZzUxlEDsYqp\nRn6eigcAsVe4GQXk5J5g/WJJgZ5eXQGraGgLbKsnZf2f8SukK0DicnwXBqfjWveM\nm174j5bfhph8/ZiKHyOes6umDCbJN5BJ6Ge6ZPYKrgO4xW+w0eQGC1ln+ZXxiG9s\nfsUgRaue0QfNnx8hJx/akYssVQKBgQDwE9UcZQ96HsbAgvitnTI1ArWOEtxjB36J\ndlTyPH5iDv9eNJMj8Sha7EaSaov244ar/NGspO34tBqeB5yFWwQnOEbENx22a3Dz\n4ZjMAV1XZ9FDtTP3vYdmNEnBm2IqR4APrFKG7orkeseJFmEi7j8Y7xDFNlHE0q3m\n2sisyZ687wKBgQDgRmDoGJWxPyZJ6+T9Vb37jRFYZEyF2Nxi7CiUpNrO8IWQ9ffG\njibwiGC5IRYf0yboECh0nAjNUdyzLiNf99CwHix2bW19YYX94jlVMYAY37zWmJSD\nI5uTgR/uGPxClWntNceCKz4iX8s4l3lLzMGTmtZXJm0NC1K0ttkk9s+GLQKBgHTh\nEuWKBejsRtK+cJcFasYIFZ+faxADPAVsSJrN/LF8n7KbYe8jnwP0976chJuj1ZKx\nuNqWSQzFkhfRmNALqY/2g+1O7/Y5hHoXIK5hE7JT5rtR4oUADoUhe674GOiAesYm\nnN74D0KAy9ffv1akKq/W45E/iruJ3gQAC6ajWdadAoGAbelcfMUes++cglpLn1/M\ngxRdR5bootb6hA3DoEJ9ESptVcydMweSnJNqKLS2gJdYilOLH8i4GCic2ArKEEPa\nnrN60T1/Miy0mO0dF43V6OKo29UMkE8ZeA4sSfCo4oP5Oo1yzkAWDBx68WvhgJPA\nG9Vrvf+AqbHdbDU4XlB2amY=\n-----END PRIVATE KEY-----\n",
    "client_email": "go-storage-upload@crypto-airlock-335904.iam.gserviceaccount.com",
    "client_id": "110819004498077867505",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/go-storage-upload%40crypto-airlock-335904.iam.gserviceaccount.com"
  }'

google_drive_credentials: '
{
  "installed": {
    "client_id": "708448127214-ebmqoe7eehc31t4ivlsa075n158c3hqd.apps.googleusercontent.com",
    "project_id": "golang-upload-http",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_secret": "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",
    "redirect_uris": [
      "urn:ietf:wg:oauth:2.0:oob",
      "http://localhost"
    ]
  }
}'
# read README.md to know how to get google-drive credentials

aws:
  region: abc
  access_key_id: abc
  secret_access_key: abc